### ISSUE TITLE
Starred header

### ISSUE THREAD

**Issue by Porges** [denis-tingaikin/go-header#11]
It would be nice to be able to match headers like:

```
/*
 * header text
 * header text
 */
```

**Comment by denis-tingaikin** [comment]
Thanks for the feedback, will do it in 0.5.0

**Comment by ryan-bever** [comment]
FYI - For anyone finding themselves here. I found a work-around for this. I'm not entirely sure how or why it works. We are using the go-header linter inside `golangci-lint` and when configuring I am able to do the following in `.golangci.yml` (Notice the first line is not indented but the following ones are):
```yaml
linters-settings:
  goheader:
    template: |-
      * header text
       * header text2
       * header text3
```

Then in my source files I can use:
```golang
/*
 * header text
 * header text2
 * header text3
 */
```
