### ISSUE TITLE
Allow repatable line patterns / optional lines

### ISSUE THREAD

**Issue by smyrman** [denis-tingaikin/go-header#26]
Would be nice to allow optional lines

```
Copyright {{YEAR-RANGE}} {{COMPANY}}
Copyright {{YEAR-RANGE}} {{ANY_AUTHOR}} // 0-N lines matching content
```

**Comment by matzf** [comment]
Just to share an observation, it's possible to use multi-line regex to match multiple copyright lines. For my use case, this was a good enough workaround, but you won't get the check for the current year as with the ``{{YEAR}}`` or `{{YEAR-RANGE}}` magic.

Example config:
```yaml
---
values:
  regexp:
    copyright-lines: "(Copyright 20[0-9][0-9] Company Foo)(\nCopyright 20[0-9][0-9] .*)*"
template: |-
  {{copyright-lines}}

  Licensed under bla bla bla
```
