### ISSUE TITLE
tabbed header

### ISSUE THREAD

**Issue by kylrth** [denis-tingaikin/go-header#9]
I prefer a header format like this:
```go
/*
   Copyright (2021) Kyle Roth

    Licensed under the Apache License, ...
*/
```

In my `.golangci.yml` I've attempted to adjust for this in my template:

```yaml
linters-settings:
  goheader:
    values:
      const:
        NAME: Kyle Roth
    template: |
      Copyright ({{ YEAR }}) {{ NAME }}

          Licensed under the Apache License, ...  # note the extra spaces on this line
```

But I get output like this from `golangci-lint`:

```
path/to/file.go:3:1: Actual:    Licensed under the Apache License, ...
Expected:Licensed under the Apache License, ... (goheader)
```

It appears that `go-header` does not correctly handle tabbed header comments.
